name: ConstellationHB
favicon: null
layout_spectrum: 0.6874303254298866
typography_spectrum: 0.5530810281634331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.44103488442488015
  lightness: 0.00002665957435965538
  saturation: 0.4017974934540689
  rhythmicContrast: 0.9896980626508594
purpose: []
