name: ConstellationHB
favicon: null
layout_spectrum: 0.50698
typography_spectrum: 0.63829
title: Constellation HomeBuilder Systems
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2328547-15
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004794'
    - '#ffd659'
    - '#231f20'
    - '#000000'
    - '#0000ff'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
